version: '3'
services:
  app:
    build: .
    ports:
      - "8484:8484"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/postgresdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
  db:
    container_name: db_name
    hostname: db_postgres
    image: postgres:11.5
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
#    volumes:
#      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql